
- name: Add apt.postgresql.org
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

- name: Add key for apt.postgresql.org
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present


# # XXX: Why the old version is installed?
# - name: Remove old postgresql versions
#   shell: apt-get purge -y --force-yes postgresql-9.1 postgresql-client-9.1
#   ## XXX: Why this fails?
#   # action: apt pkg={{item}} state=absent purge=yes force=yes
#   # with_items:
#   #   - postgresql-9.1
#   #   - postgresql-client-9.1

- name: install postgresql
  apt: pkg=postgresql-9.3 state=present force=yes update_cache=yes
  environment: postgresql_env

- name: Create databases
  sudo_user: postgres
  environment: postgresql_env
  action: postgresql_db name={{item}}
                        encoding=UTF-8
                        lc_collate={{ postgresql_locale }}
                        lc_ctype={{ postgresql_locale }}
                        template=template0
  with_items:
    - puavo-ticket
    - puavo-ticket-test

- name: Add Postgresql user
  sudo_user: postgres
  postgresql_user: name=puavo-ticket password=password role_attr_flags=LOGIN

- name: Grant permissions to postgres user for puavo-ticket databases
  sudo_user: postgres
  action: postgresql_privs db={{item}}
                           privs=ALL
                           type=database
                           roles=puavo-ticket
  with_items:
    - puavo-ticket
    - puavo-ticket-test
