- name: Install redis for puavo-ticket
  apt: pkg=redis-server state=present

- name: Get hostname
  command: hostname -f
  register: hostname_command

- name: Install puavo-ticket
  apt: pkg=puavo-ticket state=latest
  notify: Run puavo-ticket migrations

- name: Configuration for puavo-ticket
  template: src=_config.json.tmpl dest=/etc/puavo-ticket/config.json
  notify: Restart puavo-ticket
