- name: Install slapd-restore helper
  copy:
    src: slaprestore
    dest: /usr/local/bin/slaprestore
    mode: a+x

- name: Install latest puavo-standalone, puavo-web, puavo-web-worker and puavo-rest
  action:
    apt pkg={{item}}
    state=latest
    force=yes
  with_items:
    - puavo-standalone
    - puavo-web
    - puavo-rest
    - puavo-web-worker

- name: Install redis for puavo-web & puavo-rest
  apt: pkg=redis-server state=present

  # puavo-init-standalone is installed by the puavo-standalone package, but there is also
  # a copy of the script in the repo directory. This is by design.
- name: Initialize LDAP
  command: puavo-init-standalone --unsafe-passwords opinsys.net creates=/etc/puavo

- name: Create organisations for test and development
  command: puavo-add-new-organisation --yes {{ item.organisation }} --username {{ item.username }} --password {{ item.password }} --given-name {{ item.givenname }} --surname {{ item.surname }}
    creates={{ item.creates }}
  notify: Seed LDAP database
  with_items:
    - { organisation: "hogwarts",
        username: "albus",
        password: "albus",
        givenname: "Albus",
        surname: "Dumbledore",
        creates: "/var/lib/ldap/dc=edu,dc=hogwarts,dc=fi" }
    - { organisation: "example",
        username: "cucumber",
        password: "cucumber",
        givenname: "cucumber",
        surname: "cucumber",
        creates: "/var/lib/ldap/dc=edu,dc=example,dc=fi" }
    - { organisation: "anotherorg",
        username: "admin",
        password: "admin",
        givenname: "Admin",
        surname: "Administrator",
        creates: "/var/lib/ldap/dc=edu,dc=anotherorg,dc=fi" }
    - { organisation: "heroes",
        username: "admin",
        password: "admin",
        givenname: "Charles",
        surname: "Xavier",
        creates: "/var/lib/ldap/dc=edu,dc=heroes,dc=fi" }

- name: Install call-until-ok
  copy:
    dest: /usr/local/bin/call-until-ok
    mode: a+x
    content: |
      #!/bin/sh
      for i in $(seq 60); do
          >/dev/null "$@" &&  exit 0
          sleep 1
      done
      exit 1

- name: Refresh organisations for puavo-rest
  service: name=puavo-rest state=restarted

- name: Wait for puavo-rest to wake up
  command: 'call-until-ok curl --noproxy localhost --fail -H "host: hogwarts.opinsys.net" http://localhost:9292/v3/ldap_connection_test'

- name: Get hostname
  command: hostname -f
  register: hostname_command

- name: Configuration for puavo-rest
  copy:
    src=puavo-rest.yml
    dest=/etc/puavo-rest.yml
  notify: Restart puavo-rest

- name: Ensure /etc/puavo-web exists
  file:
    dest=/etc/puavo-web
    state=directory

- name: Add ldap configuration for puavo-web
  template:
    src=etc/puavo-web/ldap.yml
    dest=/etc/puavo-web/ldap.yml
  notify: Restart puavo-web

- name: Add organisations.yml for puavo-web
  template:
    src=etc/puavo-web/organisations.yml
    dest=/etc/puavo-web/organisations.yml
  notify: Restart puavo-web

- name: Add puavo_web.yml for puavo-web
  copy:
    src=etc/puavo-web/puavo_web.yml
    dest=/etc/puavo-web/puavo_web.yml
  notify: Restart puavo-web

- name: Add puavo_external_files.yml for puavo-web
  copy:
    src=etc/puavo-web/puavo_external_files.yml
    dest=/etc/puavo-web/puavo_external_files.yml
  notify: Restart puavo-web

- name: Add secrets.yml for puavo-web
  copy:
    src=etc/puavo-web/secrets.yml
    dest=/etc/puavo-web/secrets.yml
  notify: Restart puavo-web

- name: Add redis.yml for puavo-web
  copy:
    src=etc/puavo-web/redis.yml
    dest=/etc/puavo-web/redis.yml
  notify: Restart puavo-web

- name: Add unicorn.rb for puavo-web
  copy:
    src=etc/puavo-web/unicorn.rb
    dest=/etc/puavo-web/unicorn.rb
  notify: Restart puavo-web

# -------------------------------------------------------------------------------------------------
# The following hacks are copied almost verbatim from puavo-web ansible rules.
# They should be done using Debian's installation scripts or packaging scripts,
# but they aren't.

# Asset building is currently partially broken. The font files are (AFAIK) correctly named,
# but the CSS continues to refer to the "plain" names. I tried to fix this, but failed. So
# until we rewrite all of the styles (which will happen *soon*), we'll have to do one ugly
# hack to make the buttons work. The hexadecimal IDs in the filenames are SHA256 hashes of
# the respective file's contents.
- name: Ugly font linking hack
  file:
    src="/var/app/puavo-web/public/assets/font/fontello-puavo/font/{{ item.source }}"
    dest="/var/app/puavo-web/public/assets/font/fontello-puavo/font/{{ item.dest }}"
    state=link
  with_items:
    - { source: 'puavo-icons-5006b6853b3fbf65bb14ea6e41709fd0a8d51e84f0f3cff0d76709d226ab67a0.eot', dest: 'puavo-icons.eot' }
    - { source: 'puavo-icons-513eb681d0001873965e6df346f90a86ac7ea4c5a9536a09723448264b9cf139.svg', dest: 'puavo-icons.svg' }
    - { source: 'puavo-icons-85edd5d8dda0e3698eb81262bae5ebdc008231cbc620ec5a8f5feded42562774.ttf', dest: 'puavo-icons.ttf' }
    - { source: 'puavo-icons-8d7155d253af5a5eefb7c0bb2b0f122af8b680e515c76157f0439d4a2a1e2a7d.woff', dest: 'puavo-icons.woff' }

- name: Tell systemd to start the puavo services at boot
  command: systemctl enable "{{ item }}.service"
  with_items:
    - puavo-web
    - puavo-web-worker
    - puavo-rest
    - puavo-ca-rails
