
- name: Add archive.opinsys.fi/puavo-os
  apt_repository: repo='deb http://{{ archive_server }}/puavo-os {{ ansible_lsb.codename }} main' state=present update_cache=yes

- name: Add key for archive.opinsys.fi
  apt_key: data="{{ lookup('file', 'opinsys-archive.key') }}" state=present

- name: Add higher priority for puavo-os packages in archive.opinsys.fi
  template:
    src=etc/apt/preferences.d/00-puavo.pref
    dest=/etc/apt/preferences.d/00-puavo.pref

- name: Install fluentd
  apt: pkg=fluentd state=present force=yes

- name: Install development tools
  action: apt pkg={{item}} state=present force=yes
  with_items:
    - puavo-devscripts
    - build-essential
    - tmux
    - git
    - wget
    - curl
    - bash-completion
    - inotify-tools
    - vim-nox
    - git

- name: Enable /etc/sudoers.d (not enable by default in precise)
  lineinfile: dest=/etc/sudoers state=present regexp='^#includedir \/etc\/sudoers\.d$' line='#includedir /etc/sudoers.d' validate='visudo -cf %s'
