
- name: Add archive.opinsys.fi/git-master
  apt_repository: repo='deb http://{{ archive_server }}/git-master precise main' state=present update_cache=yes

- name: Add key for archive.opinsys.fi
  apt_key: url=http://{{ archive_server }}/key state=present

- name: Install development tools
  action: apt pkg={{item}} state=present force=yes
  with_items:
    - puavo-devscripts
    - aptirepo-upload
    - build-essential
    - tmux
    - git
    - wget
    - curl
    - bash-completion
    - inotify-tools
    - vim-nox
    - git

- name: Enable /etc/sudoers.d (not enable by default in precise)
  lineinfile: dest=/etc/sudoers state=present regexp='^#includedir \/etc\/sudoers\.d$' line='#includedir /etc/sudoers.d' validate='visudo -cf %s'
