
- name: Add key for archive.opinsys.fi
  apt_key:
    data="{{ lookup('file', 'opinsys-archive.key') }}"
    state=present

- name: Add archive.opinsys.fi/puavo-os
  apt_repository:
    repo='deb http://{{ archive_server }}/{{item}} {{ ansible_lsb.codename }} main'
    state=present
    update_cache=yes
  with_items:
    - puavo-os
    - puavo-web
    - puavo/

- name: Add higher priority for puavo-os packages in archive.opinsys.fi
  template:
    src=etc/apt/preferences.d/00-puavo.pref
    dest=/etc/apt/preferences.d/00-puavo.pref

- name: Install development tools
  action:
    apt pkg={{item}}
    state=present
    force=yes
  with_items:
    - bash-completion
    - build-essential
    - curl
    - git
    - inotify-tools
    - puavo-devscripts
    - sudo
    - tmux
    - vim-nox
    - wget
